### ISSUE TITLE
Custom parsing

### ISSUE THREAD

**Issue by cliren** [infinum/iOS-prince-of-versions#13]
The android version : https://github.com/infinum/Android-Prince-of-Versions supports the following feature. How can we achieve the same on iOS?

- Accept custom parser for parsing update configuration

**Comment by fgulan** [comment]
Sorry for the late response, but can you describe how would you use custom parser? 

Asking because we are doing simple JSON parsing only, and that's the core of the lib, so I'm not sure if it makes sense to expose another method for custom parsing since maybe your response will not include needed params for checking minimum version (latest_version, minimum_version, ios).
